### PR TITLE
Fix Profile Command (See Desc) 

### LINKED ISSUE #157: Profile command doesn't work for some members.
Currently when you request a profile via the profile command it works for some but not for others.
Currently doesn't work for `Timmy` * `SirSecurity`

### PR DESCRIPTION
**Pull request by DraxCodes**
Fixes #157 

## Changes
Fixed an issue with the profile command.
The issue was caused due to the DB check for an existing user. It was comparing the Guild ID's which when you're using the command from a different server, would change.
This in turn would cause the code to jump into the `Store()` method rather than the `Update()` method (For an already existing user).
It would then throw an error stating it cannot insert the same data twice.

Removing the Guild ID check fixed the issue. It's still safe too as User Id's are unique.

## Expected Feedback
I would ideally like someone else to also test this in a different server to ensure it is acting correctly.

### CODE REVIEW

**Comment by petrspelos** [comment]
From what I understand, we wanted to have the accounts local (local to each guild).
While this would fix the issue, it would also make the accounts global. 🤔

**Comment by DraxCodes** [comment]
If we want to have the accounts local then we will have to rethink how we store the data. I wasn't aware that local accounts where a thing at this moment in time.

**Comment by petrspelos** [comment]
Yeah, you want to perhaps do that in this PR?

**Comment by DraxCodes** [comment]
Personally I would rather get this PR merged to close the issue and open a new issue to redesign the user storage system as i have some questions, first and foremost regarding, I don't think we should be storing the data we currently are. At the moment is seems like an extra step that is simply redundant. 

If someone would be happy to merge this PR I will create a new issue regarding User Info Storage. ☺

**Comment by petrspelos** [comment]
With all due respect, there is no point in merging this if we're about to rework it.
The way I see it, we should close this and create a new Issue.

**Pull request closed without merging**
