### PR TITLE
Empty or invalid token UI handling #148 

### LINKED ISSUE #138: Add option to set token manually
## About

Currently, the only way to get the Windows application to accept your token is to have it copied in your clipboard.

There should be an option in the `SettingsPage` to input the token manually.

:bulb: This option should perhaps be disabled when the bot is connected.

### LINKED ISSUE #148: Empty or invalid token UI handling
## About

When no bot token is set, Miunie crashes on start.
While this should be handled in the Core, the GUI shouldn't let the user get that far.

So the task is to make sure the user doesn't start the bot when there is no token set **and** they understand the reason.

## The How

💡 One option is to disable the button and add a warning text underneath it.

### PR DESCRIPTION
**Pull request by CakeAndBanana**
## Related Issue
Fixes #148 

## Changes
Added ErrorMessage under the button, Button can be pressed but nothing will happen when there is no Discord Token set.

## Expected Feedback
Do you think this position of the ErrorMessage is good enough or does it has to be a popup or something similiar.

### CODE REVIEW

**Comment by CakeAndBanana** [comment]
I also found out that if I was to expect an exception on the bad token, It wouldn't give out an exception, only the message of bad token. I was trying to catch the error with try catch but couldn't get it because there is no exception.

**Comment by Ggglitch** [comment]
> I also found out that if I was to expect an exception on the bad token, It wouldn't give out an exception, only the message of bad token. I was trying to catch the error with try catch but couldn't get it because there is no exception.

You can't catch the exception on UI level because I made a try-catch for exception on lower level, as it was stated in issue #149 . So yeah, you can't change logged message on UWP.
But, you can open a new issue and propose to let ConsoleApp or UWP client handle exception, if that makes sense.

**Comment by CakeAndBanana** [comment]
> ated in issue #149 . So yeah, you can't change logged message on UWP.
> But, you can open a new issue and propose to let ConsoleApp or UWP client handle exception, if that makes sense.

Ah okay, I will make a issue for error handling inside UWP/ConsoleApp when I'm back from work :)

**Comment by petrspelos** [comment]
The thing is, #168 was assigned to me. This is why you guys need to really make sure you know what you're assigned to and communicate a little better.

One of us did ultimately waste their time. 🤔

**Comment by petrspelos** [comment]
In the end, the most just outcome is to go by who is assigned to what.
So, @CakeAndBanana, if you could revert your #168 changes, we can merge this.

**Comment by CakeAndBanana** [comment]
I have reverted the changes of #168 ;)

**Pull request merged**
